version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - "80:80"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app/src
    restart: unless-stopped